# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  {% if cookiecutter.project_packages in ["Todo", "Python"] -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyprojroot
  {% endif -%}
  
  {% if cookiecutter.project_packages in ["Todo", "R"] -%}
  - r-base
  - r-tidyverse
  - r-rmarkdown
  - r-shiny
  - r-rcpp
  - r-rsqlite
  - r-caret
  {% endif -%}

  - pip
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages in ["Todo", "Python"] -%}
    - pyhere
    {% endif -%}
